services:
  frontend:
    image: torii-frontend:latest
    ports: 
      - "8080:80"
    depends_on:
      backend:
        condition: service_started

  backend:
    image: torii-backend:latest
    restart: always
    command:
      --config /tmp/examples/config.yaml
    ports:
      - '9999:9999'
    volumes:
    - type: bind
      source: ./backend
      target: /tmp
